#!/bin/bash
#
# Pre-commit hook that verifies if all tfvars files are encrypted

EXIT_STATUS=0
wipe="\033[1m\033[0m"
yellow='\033[1;33m'
red='\e[0;31m'
green='\e[0;32m'
# carriage return hack. Leave it on 2 lines.
cr='
'

for f in $(git diff --cached --name-only)
do
  # test for the presence of the required bit.
  MATCH=`head -n4 $f | grep --no-messages -- "terraform_version"`
  if [ ! -z "$MATCH" ] ; then
    # Build the list of unencrypted files if any
    UNENCRYPTED_FILES="$f$cr$UNENCRYPTED_FILES"
    EXIT_STATUS=1
  fi
done

if [ ! $EXIT_STATUS = 0 ] ; then
  echo '# COMMIT POSTPONED'
  echo '# Looks like unencrypted terraform.tfstate files are part of the commit:'
  echo '#'
  while read -r line; do
    if [ -n "$line" ]; then
      echo -e "#\t${yellow}unencrypted:   $line${wipe}"
    fi
  done <<< "$UNENCRYPTED_FILES"
  echo '#'
  echo "# Encrypting these files now. Hit <Ctrl+C> to cancel'"
  echo "#"
  if ! $(vault token lookup > /dev/null); then
    echo "# Valid vault token required"
    echo "# Enter Vault username: "
    read -s user
    echo "# Authenticating to Vault as: ${user}"
    vault login -method=userpass username=${user} > /dev/null
  fi

  while read -r line; do
    if [ -n "$line" ]; then
      echo -ne "#\t${yellow}encrypting: $line${wipe} => "
      if sops -i -e $line > /dev/null 2>&1; then
        git add ${line}
        echo -e " ${green}success${wipe}"
      else
        echo -e " ${red}error${wipe}"
        exit 1
      fi
    fi
  done <<< "$UNENCRYPTED_FILES"

  echo "#"
  echo "# Files encrypted"
  echo "#"

  exit 0
fi
exit $EXIT_STATUS
